apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server-service
    app.kubernetes.io/part-of: argocd
  name: argocd-server-service
  namespace: argocd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32222
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 32223
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
status:
  loadBalancer: {}
