apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: tech-trends
  ports:
    - port: 3111
      targetPort: 3111
      nodePort: 32111
